### ISSUE TITLE
As an instructor I want to be able to navigate through the the different instructor pages via a drop down menu in the instructor page so that I can easily find pages for data searches that I need.

### ISSUE THREAD

**Issue by jdavalos1** [ucsb-cs56-w20/mapache-search#138]
- We want to create an instructor main page that has a drop down menu, "Hello" message, a description on how to use this page
- Display average and total # of searches per day
- Page to display most frequent/popular searches
- A list (drop down menu) that stores the data pages properly (for admin access only)
- A page that tracks data based on number of likes/searches/etc
- A page for holding all the data on the drop-down menu
- After clicking on the drop-down menu, display the data using a table/graph (how popular is the question, is the answer actually displayed, upvotes/downvotes)
- See the data in the table sorted by votes
- Check who is doing the searches (regular members or admins)

**Comment by ireneEvans** [comment]
First we would need to create the main page and the messages displayed on the main page with html. In order to display information about the average and total searches for the day we will need something to store the count every time a search is made. Then we will need to make our dropdown menu using more html and we will need to display the different data pages when clicked on in the dropdown menu. In the files containing our data pages we will need to implement the code that will take our data and display it in a table for the instructor to see.
