### ISSUE TITLE
As a user I want preset search filters that I can simply select and use - Implement specific search filters in filtered page table

### ISSUE THREAD

**Issue by maxcolbert** [ucsb-cs56-w20/mapache-search#142]

**Comment by NandhaUCSB** [comment]
To implement this, we will need to develop new html buttons on the search filter page that can be turned on or off to activate filters. Based on which filters are selected the search will only return relevant results.

**Comment by Ethkco** [comment]
- [ ] Given the user is on the filtered search page, when they input a website address to restrict the filtered search to, then a SearchParameters object will be created that contains these website restrictions, so that it may be feed to the filtered search in a separate issue.
- [ ] Given the user is on the filtered search page, when they input a time scope to restrict the filtered search to, then a SearchParameters object will be created that contains these timestamp restrictions, so that it may be feed to the filtered search in a separate issue.
- [ ] Given that a developer is working on on #134 or #147, when they start to write the code to implement these features, they should be able to use the new elements in src/main/java/edu/ucsb/cs56/mapache_search/search/SearchParameters.java to execute a filtered search.
