### ISSUE TITLE
As a user I want to be able to see what other students have found useful, which is identified by upvotes - Add searching based on upvotes

### ISSUE THREAD

**Issue by maxcolbert** [ucsb-cs56-w20/mapache-search#145]
- [x] Given when the user is on the filtered search page and checks the "Sort by highest upvotes" filter, then when the user executes a search, the search results will be sorted from highest to lowest upvotes.

**Comment by C1111111** [comment]
In order to see what other students have upvoted, we need to add a button to each links of the result page so that the user can upvote whatever they found useful and other users can see it. I might add a new field to the JSON object returned by the search engine to record the number of times that a link is upvoted.

**Comment by Ethkco** [comment]
- [ ] given the user is on the filtered search tab, when they input a minimum number of upvotes to restrict the search to and then execute the search, then the search results should display only results with at least that number of upvotes
